default_twitter: &default_twitter
  twitter_api_key: #'先ほど取得したAPI key'
  twitter_api_secret: #'先ほど取得したAPI secret'

development:
  secret_key_base: #長い文字列
  <<: *default_twitter

test:
  secret_key_base: #長い文字列
  <<: *default_twitter

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
